# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: recommendations.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15recommendations.proto\"D\n\x15RecommendationRequest\x12+\n\x0erecommendation\x18\x01 \x01(\x0b\x32\x13.BookRecommendation\"/\n\x12\x42ookRecommendation\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05title\x18\x02 \x01(\t\"J\n\x1b\x43reateRecommendationRequest\x12+\n\x0erecommendation\x18\x01 \x01(\x0b\x32\x13.BookRecommendation\"[\n\x1c\x43reateRecommendationResponse\x12+\n\x0erecommendation\x18\x01 \x01(\x0b\x32\x13.BookRecommendation\x12\x0e\n\x06status\x18\x02 \x01(\t\"\x7f\n\x1bUpdateRecommendationRequest\x12/\n\x12old_recommendation\x18\x01 \x01(\x0b\x32\x13.BookRecommendation\x12/\n\x12new_recommendation\x18\x02 \x01(\x0b\x32\x13.BookRecommendation\"_\n\x1cUpdateRecommendationResponse\x12/\n\x12old_recommendation\x18\x01 \x01(\x0b\x32\x13.BookRecommendation\x12\x0e\n\x06status\x18\x02 \x01(\t\"J\n\x1b\x44\x65leteRecommendationRequest\x12+\n\x0erecommendation\x18\x01 \x01(\x0b\x32\x13.BookRecommendation\"[\n\x1c\x44\x65leteRecommendationResponse\x12+\n\x0erecommendation\x18\x01 \x01(\x0b\x32\x13.BookRecommendation\x12\x0e\n\x06status\x18\x02 \x01(\t\"F\n\x16RecommendationResponse\x12,\n\x0frecommendations\x18\x01 \x03(\x0b\x32\x13.BookRecommendation*?\n\x0c\x42ookCategory\x12\x0b\n\x07MYSTERY\x10\x00\x12\x13\n\x0fSCIENCE_FICTION\x10\x01\x12\r\n\tSELF_HELP\x10\x02\x32\xa4\x02\n\x0fRecommendations\x12<\n\tRecommend\x12\x16.RecommendationRequest\x1a\x17.RecommendationResponse\x12\x45\n\x06\x43reate\x12\x1c.CreateRecommendationRequest\x1a\x1d.CreateRecommendationResponse\x12\x45\n\x06Update\x12\x1c.UpdateRecommendationRequest\x1a\x1d.UpdateRecommendationResponse\x12\x45\n\x06\x44\x65lete\x12\x1c.DeleteRecommendationRequest\x1a\x1d.DeleteRecommendationResponseb\x06proto3')

_BOOKCATEGORY = DESCRIPTOR.enum_types_by_name['BookCategory']
BookCategory = enum_type_wrapper.EnumTypeWrapper(_BOOKCATEGORY)
MYSTERY = 0
SCIENCE_FICTION = 1
SELF_HELP = 2


_RECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['RecommendationRequest']
_BOOKRECOMMENDATION = DESCRIPTOR.message_types_by_name['BookRecommendation']
_CREATERECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['CreateRecommendationRequest']
_CREATERECOMMENDATIONRESPONSE = DESCRIPTOR.message_types_by_name['CreateRecommendationResponse']
_UPDATERECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['UpdateRecommendationRequest']
_UPDATERECOMMENDATIONRESPONSE = DESCRIPTOR.message_types_by_name['UpdateRecommendationResponse']
_DELETERECOMMENDATIONREQUEST = DESCRIPTOR.message_types_by_name['DeleteRecommendationRequest']
_DELETERECOMMENDATIONRESPONSE = DESCRIPTOR.message_types_by_name['DeleteRecommendationResponse']
_RECOMMENDATIONRESPONSE = DESCRIPTOR.message_types_by_name['RecommendationResponse']
RecommendationRequest = _reflection.GeneratedProtocolMessageType('RecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONREQUEST,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationRequest)
  })
_sym_db.RegisterMessage(RecommendationRequest)

BookRecommendation = _reflection.GeneratedProtocolMessageType('BookRecommendation', (_message.Message,), {
  'DESCRIPTOR' : _BOOKRECOMMENDATION,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:BookRecommendation)
  })
_sym_db.RegisterMessage(BookRecommendation)

CreateRecommendationRequest = _reflection.GeneratedProtocolMessageType('CreateRecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _CREATERECOMMENDATIONREQUEST,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:CreateRecommendationRequest)
  })
_sym_db.RegisterMessage(CreateRecommendationRequest)

CreateRecommendationResponse = _reflection.GeneratedProtocolMessageType('CreateRecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _CREATERECOMMENDATIONRESPONSE,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:CreateRecommendationResponse)
  })
_sym_db.RegisterMessage(CreateRecommendationResponse)

UpdateRecommendationRequest = _reflection.GeneratedProtocolMessageType('UpdateRecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERECOMMENDATIONREQUEST,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:UpdateRecommendationRequest)
  })
_sym_db.RegisterMessage(UpdateRecommendationRequest)

UpdateRecommendationResponse = _reflection.GeneratedProtocolMessageType('UpdateRecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERECOMMENDATIONRESPONSE,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:UpdateRecommendationResponse)
  })
_sym_db.RegisterMessage(UpdateRecommendationResponse)

DeleteRecommendationRequest = _reflection.GeneratedProtocolMessageType('DeleteRecommendationRequest', (_message.Message,), {
  'DESCRIPTOR' : _DELETERECOMMENDATIONREQUEST,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:DeleteRecommendationRequest)
  })
_sym_db.RegisterMessage(DeleteRecommendationRequest)

DeleteRecommendationResponse = _reflection.GeneratedProtocolMessageType('DeleteRecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _DELETERECOMMENDATIONRESPONSE,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:DeleteRecommendationResponse)
  })
_sym_db.RegisterMessage(DeleteRecommendationResponse)

RecommendationResponse = _reflection.GeneratedProtocolMessageType('RecommendationResponse', (_message.Message,), {
  'DESCRIPTOR' : _RECOMMENDATIONRESPONSE,
  '__module__' : 'recommendations_pb2'
  # @@protoc_insertion_point(class_scope:RecommendationResponse)
  })
_sym_db.RegisterMessage(RecommendationResponse)

_RECOMMENDATIONS = DESCRIPTOR.services_by_name['Recommendations']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _BOOKCATEGORY._serialized_start=780
  _BOOKCATEGORY._serialized_end=843
  _RECOMMENDATIONREQUEST._serialized_start=25
  _RECOMMENDATIONREQUEST._serialized_end=93
  _BOOKRECOMMENDATION._serialized_start=95
  _BOOKRECOMMENDATION._serialized_end=142
  _CREATERECOMMENDATIONREQUEST._serialized_start=144
  _CREATERECOMMENDATIONREQUEST._serialized_end=218
  _CREATERECOMMENDATIONRESPONSE._serialized_start=220
  _CREATERECOMMENDATIONRESPONSE._serialized_end=311
  _UPDATERECOMMENDATIONREQUEST._serialized_start=313
  _UPDATERECOMMENDATIONREQUEST._serialized_end=440
  _UPDATERECOMMENDATIONRESPONSE._serialized_start=442
  _UPDATERECOMMENDATIONRESPONSE._serialized_end=537
  _DELETERECOMMENDATIONREQUEST._serialized_start=539
  _DELETERECOMMENDATIONREQUEST._serialized_end=613
  _DELETERECOMMENDATIONRESPONSE._serialized_start=615
  _DELETERECOMMENDATIONRESPONSE._serialized_end=706
  _RECOMMENDATIONRESPONSE._serialized_start=708
  _RECOMMENDATIONRESPONSE._serialized_end=778
  _RECOMMENDATIONS._serialized_start=846
  _RECOMMENDATIONS._serialized_end=1138
# @@protoc_insertion_point(module_scope)
